 language: scala
 dist: trusty
 scala:
   - "2.11.7"
 jdk:
   - oraclejdk7
   - openjdk7
   - oraclejdk8
   - openjdk8
 before_script:
   - sh src/test/resources/setup_travis.sh
 env:
   - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
 addons:
   # necessary to avoid openjdk buffer overflows
   hostname: localhost